- from: list-new.dhsf.xqhuyu.com
  to: 127.0.0.1:80
  https_to_http: true
- from: list-box.dhsf.xqhuyu.com
  to: 127.0.0.1:80
  https_to_http: true
- from: pc-api.jiyuhz.cn
  to: 127.0.0.1:80
  https_to_http: true
- from: pc-api.996hezi.cn
  to: 127.0.0.1:80
  https_to_http: true
- from: pc-api.996hezi.com
  to: 127.0.0.1:80
  https_to_http: true